/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.40
 * Generated at: 2021-01-11 06:19:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Enumeration;

public final class chukwonCardNew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Enumeration");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("EUC-KR");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>신규 축원카드 작성하기</title>\r\n");
      out.write("\t\t<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\tvar max_input = 10;\t\t\t\t\t\t\t// 최대 입력 가족수(레코드)\r\n");
      out.write("\t\t\t\tvar x = 1;\t\t\t\t\t\t\t\t\t\t// 레코드 갯수 초기화\r\n");
      out.write("\t\t\t\t$('.add-btn').click(function(e) {\t\t// 추가버튼의 클릭이벤트\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\tif (x < max_input) {\r\n");
      out.write("\t\t\t\t\t\tx++;\r\n");
      out.write("\t\t\t\t\t\t$('.wrapper').append(`\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"contactYN\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>가족대표연락자 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">대표(1명만) </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">대표아님 </option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"memGender\" name=\"memGender\" onchange=\"memGenderChange(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option >성별선택 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">여성 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"2\">남성 </option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"famCall\" name=\"famCall\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected>호칭선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"건명\">건명</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"곤명\">곤명</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"장남\">장남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"장녀\">장녀</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"차남\">차남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"차녀\">차녀</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"삼남\">삼남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"삼녀\">삼녀</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"손자\">손자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"손녀\">손녀</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"조부\">조부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"조모\">조모</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"부\">부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"모\">모</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"시부\">시부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"시모\">시모</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"장인\">장인</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"장모\">장모</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"형\">형(형님/오빠)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"제\">제(남동생)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"자\">자(누나/언니)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"매\">매(여동생)</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"memName\" placeholder=\"성명\" maxlength=\"5\" size=\"8\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"budaName\" placeholder=\"법명\" value=\"\" maxlength=\"5\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"solaDate\" placeholder=\"양력생년월일\" value=\"\" onfocus=\"solaToLuna()\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"lunaDate\" placeholder=\"음력생년월일\" value=\"\" onfocus=\"lunaToSola()\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"yundal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option >윤달여부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"0\">평달</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">윤달</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"ganji60_k\" placeholder=\"60간(한글)\" value=\"\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"ganji60_c\" placeholder=\"60간(한문)\" value=\"\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"ganji12\" placeholder=\"12지\" value=\"\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"mobileNum\" placeholder=\"휴대폰\" value=\"\" maxlength=\"5\" size=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"phoneNum\" placeholder=\"유선전화\" value=\"\" maxlength=\"5\" size=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"email\" placeholder=\"이메일\" value=\"\" maxlength=\"5\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"history\" placeholder=\"상담기록\" value=\"\" maxlength=\"5\" size=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"searchHint\" placeholder=\"검색힌트\" value=\"\" maxlength=\"5\" size=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t<select name=\"lotusYN\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>연등꼬리표기재 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1\">기재함 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"0\">안 함 </option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"remove-lnk\">삭제</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>`);\t\t\t\t\t\t\t\t\t\t\t\t//입력필드 1 레코드 추가\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$('.wrapper').on(\"click\", \".remove-lnk\", function(e) { // 삭제링크 클릭 이벤트\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t\t$(this).parent('div').remove();  \t// 입력필드 1 레코드 삭제\r\n");
      out.write("\t\t\t\t\tx--;\t\t\t\t\t\t\t\t\t\t\t// 입력필드수 1 감소\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tfunction memGenderChange(memGender) {\r\n");
      out.write("\t\t\t\tmGen = document.getElementsByName(\"memGender\");\r\n");
      out.write("\t\t\t\ti=0;\r\n");
      out.write("\t\t\t\tfor(;i<mGen.length;i++){\r\n");
      out.write("\t\t\t\t\tif(mGen[i]==memGender) break;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t    var man = [\"건명\",\"장남\",\"차남\",\"삼남\",\"사남\",\"손자\",\"할아버지\",\"아버지\",\"시아버지\",\"장인\",\"형(형님/오빠)\",\"제(남동생)\"];\r\n");
      out.write("\t\t\t    var women = [\"곤명\",\"장녀\",\"차녀\",\"삼녀\",\"사녀\",\"손녀\",\"할머니\",\"어머니\",\"시어머니\",\"장모\",\"자(누나/언니)\",\"매(여동생)\"];\r\n");
      out.write("\t\t\t    var target = document.getElementsByName(\"famCall\");\r\n");
      out.write("\t\t\t    if(memGender.value == \"1\")\r\n");
      out.write("\t\t\t    \tvar call = women;\r\n");
      out.write("\t\t\t    else if(memGender.value == \"2\")\r\n");
      out.write("\t\t\t    \tvar call = man;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t    target[i].options.length = 0;\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t    for (j in call) {\r\n");
      out.write("\t\t\t        var opt = document.createElement(\"option\");\r\n");
      out.write("\t\t\t        opt.value = call[j];\r\n");
      out.write("\t\t\t        opt.innerHTML = call[j];\r\n");
      out.write("\t\t\t        target[i].appendChild(opt);\r\n");
      out.write("\t\t\t    }   \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<table width=\"100%\" align=\"center\" bgcolor=\"#FFFF99\" >\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t<form name=\"chukwonCardNewForm\" method=\"post\" action=\"chukwonCardNewProc.jsp\">\r\n");
      out.write("\t\t\t\t\t");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\" align=\"center\" bgcolor=\"\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr align=\"center\" bgcolor=\"#F4F4F4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td height=\"30\"><font color=\"\"><b>가족정보 입력</b></font></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\" height=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"famGrade\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option>행사참여수준선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">항상 열심히</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">가끔 행사만 참석</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\">어쩌다 한번씩</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"4\">연락 거의 두절</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"5\">정보삭제 직전</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"noticeYN\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option >행사알림여부선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">모든 행사 알려주기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"2\">주요행사만 알려주기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"3\">행사 알릴필요 없음</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\" height=\"100\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"postcode\" id=\"postcode\" type=\"text\" placeholder=\"우편번호\" size=\"7\" readonly> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" onClick=\"execPostcode()\">우편번호 찾기</button> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"address\" id=\"address\" type=\"text\" placeholder=\"주소1\" size=\"30\" readonly> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"extraAddress\" id=\"extraAddress\" type=\"text\" placeholder=\"주소2\" size=\"30\" readonly> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input name=\"detailAddress\" id=\"detailAddress\" type=\"text\" placeholder=\"직접입력주소\" maxlength=\"20\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<table width=\"95%\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn add-btn\">가족구성원 추가하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"wrapper\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"input-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"contactYN\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option>가족대표연락자 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">대표(1명만) </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">대표아님 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select id=\"memGender\" name=\"memGender\" onchange=\"memGenderChange(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option >성별선택 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">여성 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">남성 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select id=\"famCall\" name=\"famCall\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option selected>호칭선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"건명\">건명</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"곤명\">곤명</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"장남\">장남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"장녀\">장녀</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"차남\">차남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"차녀\">차녀</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"삼남\">삼남</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"삼녀\">삼녀</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"손자\">손자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"손녀\">손녀</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"조부\">조부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"조모\">조모</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"부\">부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"모\">모</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"시부\">시부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"시모\">시모</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"장인\">장인</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"장모\">장모</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"형\">형(형님/오빠)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"제\">제(남동생)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"자\">자(누나/언니)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"매\">매(여동생)</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"memName\" placeholder=\"성명\" maxlength=\"5\" size=\"8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"budaName\" placeholder=\"법명\" value=\"\" maxlength=\"5\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"solaDate\" placeholder=\"양력생년월일\" value=\"\" onfocus=\"solaToLuna()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"lunaDate\" placeholder=\"음력생년월일\" value=\"\" onfocus=\"lunaToSola()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"yundal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option >윤달여부</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\">평달</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">윤달</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"ganji60_k\" placeholder=\"60간(한글)\" value=\"\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"ganji60_c\" placeholder=\"60간(한문)\" value=\"\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"ganji12\" placeholder=\"12지\" value=\"\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"mobileNum\" placeholder=\"휴대폰\" value=\"\" maxlength=\"5\" size=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"phoneNum\" placeholder=\"유선전화\" value=\"\" maxlength=\"5\" size=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"email\" placeholder=\"이메일\" value=\"\" maxlength=\"5\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"history\" placeholder=\"상담기록\" value=\"\" maxlength=\"5\" size=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input name=\"searchHint\" placeholder=\"검색힌트\" value=\"\" maxlength=\"5\" size=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select name=\"lotusYN\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option>연등꼬리표기재 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">기재함 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\">안 함 </option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t&nbsp; &nbsp; &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn\">저장하기</button>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"reset\" class=\"btn\">다시쓰기</button>&nbsp; \r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" onClick=\"javascript:location.href='index.jsp'\">작성취소</button>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
