/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.40
 * Generated at: 2021-01-12 06:09:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.netpidia;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/netpidia/tlogin.jsp", Long.valueOf(1610431743653L));
    _jspx_dependants.put("/netpidia/tbody.jsp", Long.valueOf(1610429406952L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>project</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>project</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");

	String id = (String)session.getAttribute("idKey");
	
	String log="";
	if(id == null) log ="<a href=login3.jsp>LOGIN</a>";
	else log = "<a href=logout.jsp>LOGOUT</a>";

	String reg="";
	if(id == null) reg ="<a href=join.jsp>SIGNUP</a>";
	//else reg = "<a href=update.jsp>UPDATE</a>";
	else reg = "<i class='fa fa-user-circle-o' aria-hidden='true'>";

      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<input type=\"checkbox\" id=\"chk1\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<img src=\"./image/netpidia.png\" style=\"float: left; margin-top: 10px; margin-left:70px; width: 200px; height: 60px;\"/>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">Movies</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"review.jsp\">Review</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">My favorite</a></li>\r\n");
      out.write("\t\t\t<li>");
      out.print(log);
      out.write("<li>\r\n");
      out.write("\t\t\t<li><a href=\"update.jsp\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-user-circle-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t</li>\t\t\t\r\n");
      out.write("\t\t\t<label for=\"chk1\" class=\"menu-close\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-times\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t</label>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"search\" id=\"srch\" style=\"font-family:ëì\"\r\n");
      out.write("\t\t\trequired placeholder=\"Enter your search\">\r\n");
      out.write("\t\t\t<button type =\"submit\">Search</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<label for=\"chk1\" class=\"menu-open\">\r\n");
      out.write("\t\t\t<i class = \"fa fa-bars\" aria-hidden =\"true\"></i>\r\n");
      out.write("\t\t</label>\r\n");
      out.write("\t</header>");
      out.write('\r');
      out.write('\n');
      out.write('	');
if(id != null){
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img1.jpg\" >\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">위쳐</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">리비아의 게롤트는 괴물을 사냥하며 살아가는 고독한 사내. \r\n");
      out.write("\t\t\t\t\t때로는 인간이 괴물보다 사악한 이 세상에서, 그는 자신이 있어야 할 자리를 찾고자 분투한다. \t\t\t\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" onclick=\"window.open('https://youtu.be/bjSnsUFPxLI','예고편','resizable=no, width=1000, height=800, left='+ popupX + ', top='+ popupY);return false\"> <!-- 유튜브주소 -->\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">종이의 집</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">신원미상의 '교수'라 불리는 남자가 모은 8명의 범죄자들은 \r\n");
      out.write("\t\t\t\t\t톨레도의 한 사냥터에서 마드리드 조폐국을 털기 위해 몇 달간 숙식을 하면서 교수의 작전에 동참한다. \r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" onclick=\"window.open('https://youtu.be/mFGXuFZ-a9k','예고편','resizable=no, width=1000, height=800, left='+ popupX + ', top='+ popupY);return false\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용내용내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img4.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img7.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img8.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img9.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img10.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<h2>recommend</h2>\r\n");
      out.write("\t\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t\t<div class=\"nav-bar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"column active\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img4.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img7.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img8.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img9.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img10.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"prev\"><</div>\r\n");
      out.write("\t\t\t<div class=\"next\">></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>");
      out.write('\r');
      out.write('\n');
      out.write('	');
}else{
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img1.jpg\" >\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">위쳐</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">리비아의 게롤트는 괴물을 사냥하며 살아가는 고독한 사내. \r\n");
      out.write("\t\t\t\t\t때로는 인간이 괴물보다 사악한 이 세상에서, 그는 자신이 있어야 할 자리를 찾고자 분투한다. \t\t\t\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" onclick=\"window.open('https://youtu.be/bjSnsUFPxLI','예고편','resizable=no, width=1000, height=800, left='+ popupX + ', top='+ popupY);return false\"> <!-- 유튜브주소 -->\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">종이의 집</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">신원미상의 '교수'라 불리는 남자가 모은 8명의 범죄자들은 \r\n");
      out.write("\t\t\t\t\t톨레도의 한 사냥터에서 마드리드 조폐국을 털기 위해 몇 달간 숙식을 하면서 교수의 작전에 동참한다. \r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" onclick=\"window.open('https://youtu.be/mFGXuFZ-a9k','예고편','resizable=no, width=1000, height=800, left='+ popupX + ', top='+ popupY);return false\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용내용내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img4.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img7.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img8.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img9.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"slides\">\r\n");
      out.write("\t\t\t\t<img src=\"./image/img10.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t<h2 style=\"font-weight: bold; font-family:돋움\">제목</h2>\r\n");
      out.write("\t\t\t\t\t<p style=\"font-weight: bold; font-family:돋움\">내용\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-play\" aria-hidden=\"true\"></i>\r\n");
      out.write("\t\t\t\t\t\tWatch trailer\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<h2>recommend</h2>\r\n");
      out.write("\t\t\t<div class=\"nav\">\r\n");
      out.write("\t\t\t\t<div class=\"nav-bar\">\r\n");
      out.write("\t\t\t\t\t<div class=\"column active\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img1.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img2.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img3.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img4.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img5.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img6.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img7.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img8.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img9.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"./image/img10.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"prev\"><</div>\r\n");
      out.write("\t\t\t<div class=\"next\">></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>");
      out.write('\r');
      out.write('\n');
      out.write('	');
}
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tconst slides = document.querySelectorAll('.slides');\r\n");
      out.write("\t\tconst dots = document.querySelectorAll('.column');\r\n");
      out.write("\t\tlet slideIndex = 0;\r\n");
      out.write("\t\tshowSlide();\r\n");
      out.write("\t\tfunction showSlide(n){\r\n");
      out.write("\t\t\tif(slideIndex > slides.length -1){\r\n");
      out.write("\t\t\t\tslideIndex = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(slideIndex < 0){\r\n");
      out.write("\t\t\t\tslideIndex = slides.length -1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor(let i=0; i<slides.length; i++){\r\n");
      out.write("\t\t\t\tslides[i].style.display =\"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor(let i=0; i<dots.length; i++){\r\n");
      out.write("\t\t\t\tdots[i].className = dots[i].className.replace(\" active\", \"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tslides[slideIndex].style.display = \"block\";\r\n");
      out.write("\t\t\tdots[slideIndex].className += \" active\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdots.forEach((item, index) =>{\r\n");
      out.write("\t\t\titem.addEventListener('click', ()=>{\r\n");
      out.write("\t\t\t\tshowSlide(slideIndex = index);\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconst nav = document.querySelector('.nav');\r\n");
      out.write("\t\tconst prev = document.querySelector('.prev');\r\n");
      out.write("\t\tconst next = document.querySelector('.next');\r\n");
      out.write("\t\tnext.addEventListener('click', ()=>{\r\n");
      out.write("\t\t\tnav.scrollLeft += dots[0].offsetWidth;\r\n");
      out.write("\t\t\tshowSlide(slideIndex += 1);\r\n");
      out.write("\t\t\tif(slideIndex === 0){\r\n");
      out.write("\t\t\t\tnav.scrollLeft = 0;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\tprev.addEventListener('click', ()=>{\r\n");
      out.write("\t\t\tnav.scrollLeft -= dots[0].offsetWidth;\r\n");
      out.write("\t\t\tshowSlide(slideIndex -= 1);\r\n");
      out.write("\t\t\tif(slideIndex === slides.length -1){\r\n");
      out.write("\t\t\t\tnav.scrollLeft = nav.scrollWidth;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar popupX = (document.body.offsetWidth / 2) - (1000 / 2);\r\n");
      out.write("\t\t//&nbsp;만들 팝업창 좌우 크기의 1/2 만큼 보정값으로 빼주었음\r\n");
      out.write("\r\n");
      out.write("\t\tvar popupY= (window.screen.height / 2) - (800 / 2);\r\n");
      out.write("\t\t//&nbsp;만들 팝업창 상하 크기의 1/2 만큼 보정값으로 빼주었음\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
